### ISSUE TITLE
[Mechanics] Sketches have undefined elements

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-teletupsud#1]
Many of the parts (e.g. slide, sein) have undefined (blue lines) elements in the sketches. Sketches need to be fully defined (black lines).

![Fusion360_2022-09-19_13-34-31](https://user-images.githubusercontent.com/32770145/190999503-fc91b90a-5960-4fb5-bf06-2a2f81b5bb6c.png)

**Comment by KaarelJ98** [comment]
Resolved

**Comment by Akustav** [comment]
Accidentally duplicated the issue: https://github.com/ut-robotics/picr22-team-teletupsud/issues/6
