### ISSUE TITLE
[Mechanics] add lips for better roller centering

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#11]
I suggest adding lips to the sides of the slots where rollers are. This fixes them better in place.
One thing to keep in mind is that they should only touch the inner sleeve of the bearing since it is static, if it touches other areas, it can 

![image](https://user-images.githubusercontent.com/5435954/196123969-9af766d4-5cdd-4ddb-a5f9-be3d571e54e6.png)

**Comment by KaarelJ98** [comment]
Resolved
