### ISSUE TITLE
[Mechanics] motor-wheel mount issues

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#13]
I suggest making the mount a little thinner.

![image](https://user-images.githubusercontent.com/5435954/196124761-03d1da89-217c-4c36-bc73-91f4891273f8.png)

I would make the threaded parts (marked with number 1) around 3mm and the upper part around 8 mm.

Also, the holes in the mount should be 2.5mm instead of 3 since they are threaded.

What screw do you plan to use to fasten the wheel to the motor shaft?

**Comment by KaarelJ98** [comment]
Resolved
I was planning to use M4x6 or M4x8 screw.
