### ISSUE TITLE
[Mechanics] add hole for shaft in wheel body

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#14]
Consider adding a hole to the wheel body where the shaft can go. This allows to you more adaptability on where the wheel sits on the shaft.

![image](https://user-images.githubusercontent.com/5435954/196125360-2a6af40d-24cc-424f-9f2f-b2aca96bdf4d.png)

**Comment by KaarelJ98** [comment]
Resolved
