### ISSUE TITLE
[Mechanics] Blue lines

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#15]
There are blue lines in sketches:

![image](https://user-images.githubusercontent.com/5435954/196125569-03449406-8867-4806-9fd1-49be5a3d6478.png)

![image](https://user-images.githubusercontent.com/5435954/196125722-ee3bde95-5e93-4c68-a984-73f325340f80.png)

**Comment by KaarelJ98** [comment]
Resolved
