### ISSUE TITLE
[Mechanics] Use circle or arc for slide C-ramp

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-teletupsud#2]
Do not use a spline for the C-ramp of the slide. Use a circle or arc, with its center set on the center of the motor.

![Fusion360_2022-09-19_13-06-46](https://user-images.githubusercontent.com/32770145/190999713-158dcb09-fa38-406c-852e-d8476b7debc7.png)

**Comment by KaarelJ98** [comment]
Resolved
