### ISSUE TITLE
[Mechanics] Fix dogbones

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-teletupsud#4]
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/mechanics/design.html#_inside_sharp_corners

The dogbones in the side walls are not fully defined and not properly placed.
Follow the guide linked above.

![Fusion360_2022-09-19_13-42-21](https://user-images.githubusercontent.com/32770145/191000654-52e99bba-dc02-40a5-aecc-8667b14fb072.png)

**Comment by KaarelJ98** [comment]
Resolved
