### ISSUE TITLE
Camera mount holes wrong size and could be interfer

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#50]
The current mounting holes are all 2.5 mm. Do you plan to thread everything?

Also could screw head sizes become an issue?

![image](https://user-images.githubusercontent.com/5435954/204080179-9e233e2b-f504-40f4-88f9-d9fe8484ebb9.png)

**Comment by KaarelJ98** [comment]
The stands should actually have 3mm holes, fixed them. I think the screws will fit, if not then I can drill the holes a bit to the left.
