### ISSUE TITLE
[Mechanics] bottom plate-thrower mating weird

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-teletupsud#8]
Seems like there is some interference between the thrower tabs and the thower:

![image](https://user-images.githubusercontent.com/5435954/192138259-b0907664-2f83-4f05-9677-a5b8f31439bf.png)

It also seems that the mounting holes are weirdly placed and not centered:
![image](https://user-images.githubusercontent.com/5435954/192138284-8de40f96-061a-4d27-8352-76f9afd4aec5.png)
![image](https://user-images.githubusercontent.com/5435954/192138296-c7db5079-37a8-41c0-bbcf-ed77875e1c02.png)

**Comment by KaarelJ98** [comment]
Resolved
